name: flutter_user_idle
description: "Detect user inactivity (idle state) in Flutter apps."
version: 0.0.1
homepage: https://github.com/AZHARKC/flutter_user_idle
repository: https://github.com/AZHARKC/flutter_user_idle
issue_tracker: https://github.com/AZHARKC/flutter_user_idle/issues

license: MIT

topics:
  - idle
  - inactivity
  - session-timeout
  - user-behavior


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
